### ISSUE TITLE
Add tests for `was-tx-mined` and `was-segwit-tx-mined-compact`

### ISSUE THREAD

**Issue by jose-compu** [friedger/clarity-bitcoin#22]
These two functions lacks testing:

- Add tests for `was-tx-mined` with mined and non-mined cases.
- Add tests for `was-segwit-tx-mined-compact` with mined and non-mined cases.

These are complex cases.

**Comment by friedger** [comment]
Tests has been added, e.g. https://github.com/friedger/clarity-bitcoin/blob/main/contracts/tests/clarity-bitcoin_segwit_test.clar
