### ISSUE TITLE
Should v5 be considered the latest canonical contract now?

### ISSUE THREAD

**Issue by ECBSJ** [friedger/clarity-bitcoin#28]
I've noticed the `clarity-bitcoin-lib-v5` contract has been deployed to mainnet here:

https://explorer.hiro.so/txid/0xfe25941d97a1b965b09699b622ec1d701997be62708dbac2e7a8c36a49e3e9bc?chain=mainnet

But the readme and version tag is still on v4. Should v5 now be considered the canonical contract?

**Comment by friedger** [comment]
Indeed, a new release has been created and the Readme updated
