### ISSUE TITLE
Document main methods

### ISSUE THREAD

**Issue by friedger** [friedger/clarity-bitcoin#3]
Main methods are
* was-tx-mined
* parse-block-header

To verify the parameters before calling a contract call that uses `was-tx-mined` (see e.g. https://github.com/friedger/stacks-swaps/blob/73b44fb466485f9f3d5554e77cf21068bdd4ee6a/src/components/SwapSubmit.jsx#L60), these methods are helpful:
* verify-block-header
* verify-merkle-proof

Maybe something from here can be reused: https://docs.catamaranswaps.org/en/latest/

**Comment by Teke-pixel** [comment]
Awesome 👏 very helpful

**Comment by friedger** [comment]
Content from readme was duplicated here: 
https://clarity-bitcoin.gitbook.io/clarity-bitcoin-library/
https://github.com/stacks-network/docs/pull/1589

**Comment by friedger** [comment]
Readme and gitbook were updated
