### ISSUE TITLE
[2.1] Remove `inner-buff32-permutation`

### ISSUE THREAD

**Issue by jcnelson** [friedger/clarity-bitcoin#5]
Hey @friedger, great work on porting this library to Clarity 2!

I just wanted to let you know that the function `inner-buff32-permutation` can be removed, and replaced with a series of `element-at?` and `replace-at?` calls in `reverse-buff32`.  This would remove the need to run 32 calls to `concat`.  This should save you a lot of runtime, because `concat`-ing two sequences of lengths _m_ and _n_ has runtime complexity _O(m + n)_, whereas `element-at?` is _O(1)_ and `replace-at?` is _O(s)_ where _s_ is the size of one item in the sequence (for `buff`, _s = 1_).

**Comment by friedger** [comment]
Thank you for the suggestion @jcnelson. Implemented in #6 
We see a reduction in runtime costs from 0.08% to 0.02%
